In [1]:
import pandas as pd
# import numpy as np
import seaborn as sns
qb = pd.read_excel("../Python_data/qbgradeTEST1.xlsx")
qb = qb.rename(columns={"CORRECT PRESNAP ALLIGNMENT": "CORRECT PRESNAP ALIGNMENT"})
qb = qb.rename(columns={"SIGHT ADJUST": "LEVERAGE"})
qb

,PERIOD,DN,DIST,YARD LN,HASH,GN/LS,PERSONNEL,QB#,PLAY TYPE,PLAY RESULT,...,CORRECT SIDE,PROGRESSION UNDER PRESSURE,LEVERAGE,DROPBACK,ALIGNMENT,BALL SECURITY,LAUNCHPOINT,THROW ON RUN,BLITZ,COVERAGE
0,Gold Zone,1,10,83,L,0,12,17,Pass,Incomplete,...,0.0,0.0,0.0,0.5,0.5,1.0,0.5,No,Yes,Mixed
1,Green Zone,2,8,15,M,-7,11,6,Pass,Sack,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,No,No,Man
2,Third Down Team,3,4,63,M,4,12,17,Pass,Complete,...,0.0,1.0,1.0,0.0,1.0,0.5,0.0,No,No,Zone
3,Skelly,2,10,23,R,0,12,6,Pass,Complete,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,No,No,Man
4,Gold Zone,1,10,83,L,3,12,17,Pass,Complete,...,1.0,0.0,0.0,0.5,1.0,1.0,0.0,No,No,Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Green Zone,2,4,7,R,0,11,12,Pass,Incomplete,...,1.0,0.5,0.0,0.0,0.0,0.0,1.0,No,Yes,Man
96,TeamRun,1,10,80,R,9,11,10,Run,Gain,...,0.5,0.0,0.0,1.0,1.0,0.0,0.5,NaN,No,Zone
97,Third Down Team,3,9,27,M,3,12,17,Pass,Complete,...,0.0,1.0,0.0,1.0,1.0,1.0,0.5,No,No,Zone
98,Team,1,10,30,L,4,12,6,Pass,Complete,...,0.5,1.0,1.0,0.0,1.0,0.0,1.0,No,Yes,Zone
99,Redzone,1,10,13,R,4,12,10,Pass,Complete,...,1.0,1.0,1.0,0.0,0.5,0.0,1.0,No,Yes,Man

In [8]:
# Creating the PRESNAP Grade
presnap_cols = ['CORRECT POINT', 'CORRECT PRESNAP ALIGNMENT', 'SET PROTECTION', 'FIRST LOOK']

qb[presnap_cols] = qb[presnap_cols].apply(pd.to_numeric, errors='coerce')
qb[presnap_cols] = qb[presnap_cols].fillna(qb[presnap_cols].mean())
qb["PRESNAP_GRADE"] = qb[presnap_cols].sum(axis=1)

In [9]:
# Creating the PASSING_GRADE
passing_cols = ['THROW DIFFICULTY', 'THROW PLACEMENT', 'THROW TIMING', 'TURNOVER WORTHY']

qb[passing_cols] = qb[passing_cols].apply(pd.to_numeric, errors='coerce')
qb[passing_cols] = qb[passing_cols].fillna(qb[passing_cols].mean())
qb["PASSING_GRADE"] = qb[passing_cols].mean(axis=1)

In [10]:
# Creating the ATHLETIC Grade
athletic_cols = ['ELUSIVENESS', 'ARM ANGLE', 'EYES DOWNFIELD', 'ESCAPABILITY']

qb[athletic_cols] = qb[athletic_cols].apply(pd.to_numeric, errors='coerce')
qb[athletic_cols] = qb[athletic_cols].fillna(qb[athletic_cols].mean())
qb["ATHLETIC_GRADE"] = qb[athletic_cols].sum(axis=1)

In [11]:
# Creating the POSTSNAP Grade
postsnap_cols = ['CORRECT READ', 'CORRECT SIDE', 'PROGRESSION UNDER PRESSURE', 'LEVERAGE']

qb[postsnap_cols] = qb[postsnap_cols].apply(pd.to_numeric, errors='coerce')
qb[postsnap_cols] = qb[postsnap_cols].fillna(qb[postsnap_cols].mean())
qb["POSTSNAP_GRADE"] = qb[postsnap_cols].sum(axis=1)

In [12]:
# Creating the MECHANICS Grade
mechanics_cols = ['DROPBACK', 'ALIGNMENT', 'BALL SECURITY', 'LAUNCHPOINT']

qb[mechanics_cols] = qb[mechanics_cols].apply(pd.to_numeric, errors='coerce')
qb[mechanics_cols] = qb[mechanics_cols].fillna(qb[mechanics_cols].mean())
qb["MECHANICS_GRADE"] = qb[mechanics_cols].sum(axis=1)

In [13]:
qb

,PERIOD,DN,DIST,YARD LN,HASH,GN/LS,PERSONNEL,QB#,PLAY TYPE,PLAY RESULT,...,BALL SECURITY,LAUNCHPOINT,THROW ON RUN,BLITZ,COVERAGE,PRESNAP_GRADE,PASSING_GRADE,ATHLETIC_GRADE,POSTSNAP_GRADE,MECHANICS_GRADE
0,Gold Zone,1,10,83,L,0,12,17,Pass,Incomplete,...,1.0,0.5,No,Yes,Mixed,1.5,1.87500,2.5,1.0,2.5
1,Green Zone,2,8,15,M,-7,11,6,Pass,Sack,...,1.0,0.0,No,No,Man,0.5,2.00000,0.0,0.0,1.0
2,Third Down Team,3,4,63,M,4,12,17,Pass,Complete,...,0.5,0.0,No,No,Zone,3.0,2.00000,1.0,3.0,1.5
3,Skelly,2,10,23,R,0,12,6,Pass,Complete,...,1.0,1.0,No,No,Man,1.0,2.00000,2.0,1.0,3.0
4,Gold Zone,1,10,83,L,3,12,17,Pass,Complete,...,1.0,0.0,No,No,Zone,1.5,2.87500,2.5,2.0,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Green Zone,2,4,7,R,0,11,12,Pass,Incomplete,...,0.0,1.0,No,Yes,Man,2.0,2.12500,3.0,1.5,1.0
96,TeamRun,1,10,80,R,9,11,10,Run,Gain,...,0.0,0.5,NaN,No,Zone,1.5,2.28125,2.5,1.0,2.5
97,Third Down Team,3,9,27,M,3,12,17,Pass,Complete,...,1.0,0.5,No,No,Zone,2.0,2.50000,2.0,1.0,3.5
98,Team,1,10,30,L,4,12,6,Pass,Complete,...,0.0,1.0,No,Yes,Zone,3.0,2.25000,2.5,3.0,2.0
99,Redzone,1,10,13,R,4,12,10,Pass,Complete,...,0.0,1.0,No,Yes,Man,3.5,2.00000,2.5,3.0,1.5