In [18]:
import pandas as pd
# import numpy as np
import seaborn as sns
qb = pd.read_excel("../Python_data/qbgradeTEST1.xlsx")
qb

,PERIOD,DN,DIST,YARD LN,HASH,GN/LS,PERSONNEL,QB#,PLAY TYPE,PLAY RESULT,...,CORRECT SIDE,PROGRESSION UNDER PRESSURE,SIGHT ADJUST,DROPBACK,ALIGNMENT,BALL SECURITY,LAUNCHPOINT,THROW ON RUN,BLITZ,COVERAGE
0,Gold Zone,1,10,83,L,0,12,17,Pass,Incomplete,...,0.0,0.0,0.0,0.5,0.5,1.0,0.5,No,Yes,Mixed
1,Green Zone,2,8,15,M,-7,11,6,Pass,Sack,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,No,No,Man
2,Third Down Team,3,4,63,M,4,12,17,Pass,Complete,...,0.0,1.0,1.0,0.0,1.0,0.5,0.0,No,No,Zone
3,Skelly,2,10,23,R,0,12,6,Pass,Complete,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,No,No,Man
4,Gold Zone,1,10,83,L,3,12,17,Pass,Complete,...,1.0,0.0,0.0,0.5,1.0,1.0,0.0,No,No,Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Green Zone,2,4,7,R,0,11,12,Pass,Incomplete,...,1.0,0.5,0.0,0.0,0.0,0.0,1.0,No,Yes,Man
96,TeamRun,1,10,80,R,9,11,10,Run,Gain,...,0.5,0.0,0.0,1.0,1.0,0.0,0.5,NaN,No,Zone
97,Third Down Team,3,9,27,M,3,12,17,Pass,Complete,...,0.0,1.0,0.0,1.0,1.0,1.0,0.5,No,No,Zone
98,Team,1,10,30,L,4,12,6,Pass,Complete,...,0.5,1.0,1.0,0.0,1.0,0.0,1.0,No,Yes,Zone
99,Redzone,1,10,13,R,4,12,10,Pass,Complete,...,1.0,1.0,1.0,0.0,0.5,0.0,1.0,No,Yes,Man

In [19]:
# Creating PASSING_GRADE
passing_cols = ['THROW DIFFICULTY', 'THROW PLACEMENT', 'THROW TIMING', 'TURNOVER WORTHY']

qb[passing_cols] = qb[passing_cols].apply(pd.to_numeric, errors='coerce')
qb[passing_cols] = qb[passing_cols].fillna(qb[passing_cols].mean())
qb["PASSING_GRADE"] = qb[passing_cols].mean(axis=1)


qb  # now each row (play) has PASSING_GRADE

,PERIOD,DN,DIST,YARD LN,HASH,GN/LS,PERSONNEL,QB#,PLAY TYPE,PLAY RESULT,...,PROGRESSION UNDER PRESSURE,SIGHT ADJUST,DROPBACK,ALIGNMENT,BALL SECURITY,LAUNCHPOINT,THROW ON RUN,BLITZ,COVERAGE,PASSING_GRADE
0,Gold Zone,1,10,83,L,0,12,17,Pass,Incomplete,...,0.0,0.0,0.5,0.5,1.0,0.5,No,Yes,Mixed,1.87500
1,Green Zone,2,8,15,M,-7,11,6,Pass,Sack,...,0.0,0.0,0.0,0.0,1.0,0.0,No,No,Man,2.00000
2,Third Down Team,3,4,63,M,4,12,17,Pass,Complete,...,1.0,1.0,0.0,1.0,0.5,0.0,No,No,Zone,2.00000
3,Skelly,2,10,23,R,0,12,6,Pass,Complete,...,0.0,1.0,0.0,1.0,1.0,1.0,No,No,Man,2.00000
4,Gold Zone,1,10,83,L,3,12,17,Pass,Complete,...,0.0,0.0,0.5,1.0,1.0,0.0,No,No,Zone,2.87500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Green Zone,2,4,7,R,0,11,12,Pass,Incomplete,...,0.5,0.0,0.0,0.0,0.0,1.0,No,Yes,Man,2.12500
96,TeamRun,1,10,80,R,9,11,10,Run,Gain,...,0.0,0.0,1.0,1.0,0.0,0.5,NaN,No,Zone,2.28125
97,Third Down Team,3,9,27,M,3,12,17,Pass,Complete,...,1.0,0.0,1.0,1.0,1.0,0.5,No,No,Zone,2.50000
98,Team,1,10,30,L,4,12,6,Pass,Complete,...,1.0,1.0,0.0,1.0,0.0,1.0,No,Yes,Zone,2.25000
99,Redzone,1,10,13,R,4,12,10,Pass,Complete,...,1.0,1.0,0.0,0.5,0.0,1.0,No,Yes,Man,2.00000